# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test Build and Run JUnit Tests

on:
  pull_request:
    branches: [ "develop" ]
    types: [ "opened", "reopened" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Create application-db.yml
        run: |
          touch ./src/main/resources/application-db.yml
          echo "${{ secrets.DB_YML }}" > ./src/main/resources/application-db.yml
      
      - name: Create application-swagger.yml
        run: |
          touch ./src/main/resources/application-swagger.yml
          echo "${{ secrets.SWAGGER_YML }}" > ./src/main/resources/application-swagger.yml

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test